## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [10]:
import os
import numpy as np
import pandas as pd

In [16]:
# 設定 data_path
dir_data = 'c:/abc/'

In [17]:

f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: c:/abc/application_train.csv

#### 列出所有欄位

In [24]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [18]:
app_train.head(3)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

遺失值補0

In [25]:
app_train.dropna(0)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
124,100145,0,Cash loans,F,Y,Y,1,202500.0,260725.5,16789.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
152,100179,0,Cash loans,F,Y,N,0,202500.0,675000.0,53329.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
161,100190,0,Cash loans,M,Y,N,0,162000.0,263686.5,24781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
255,100295,1,Cash loans,M,Y,N,1,225000.0,1019205.0,31032.0,...,1,0,0,0,0.0,0.0,0.0,6.0,0.0,1.0
296,100341,0,Cash loans,M,Y,Y,0,76500.0,545040.0,20677.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
298,100343,0,Cash loans,M,Y,Y,0,315000.0,90000.0,4504.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
316,100363,0,Cash loans,F,Y,Y,1,360000.0,493497.0,48942.0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,1.0
323,100371,0,Cash loans,F,Y,Y,1,450000.0,808650.0,31464.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
328,100376,0,Cash loans,M,Y,Y,0,360000.0,254700.0,20250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
337,100389,0,Cash loans,M,Y,Y,0,247500.0,1971072.0,68643.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
343,100395,0,Cash loans,M,Y,Y,0,225000.0,888840.0,32053.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
369,100425,0,Cash loans,F,Y,Y,2,90000.0,688500.0,20259.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
415,100479,0,Revolving loans,M,Y,Y,0,90000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
441,100508,0,Cash loans,F,Y,Y,0,450000.0,1971072.0,62019.0,...,0,0,0,0,0.0,0.0,0.0,0.0,4.0,1.0
483,100557,0,Cash loans,F,Y,Y,0,225000.0,1320975.0,43785.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
492,100567,1,Revolving loans,M,Y,Y,0,99000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
591,100678,0,Cash loans,F,Y,Y,2,184500.0,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
696,100805,0,Cash loans,M,Y,N,0,270000.0,1098000.0,28962.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
701,100810,0,Revolving loans,M,Y,Y,2,540000.0,900000.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
739,100852,0,Cash loans,M,Y,Y,0,157500.0,1190340.0,63549.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0
765,100879,1,Cash loans,F,Y,Y,0,450000.0,1323000.0,47650.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
803,100920,0,Cash loans,M,Y,Y,3,112500.0,832500.0,24471.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
862,100988,0,Cash loans,M,Y,Y,0,180000.0,1350000.0,38821.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
901,101038,0,Cash loans,M,Y,Y,0,180000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
917,101059,0,Cash loans,M,Y,Y,0,225000.0,454500.0,46570.5,...,0,0,0,0,0.0,0.0,0.0,4.0,0.0,2.0
1001,101158,0,Revolving loans,M,Y,Y,0,180000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1008,101166,0,Revolving loans,F,Y,N,0,157500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
1047,101216,0,Cash loans,F,Y,Y,0,135000.0,518562.0,22099.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1049,101218,0,Cash loans,M,Y,Y,0,522000.0,746280.0,59094.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306681,455319,0,Cash loans,F,Y,Y,0,225000.0,704844.0,36117.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306683,455321,0,Cash loans,F,Y,Y,0,135000.0,1026000.0,30127.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306699,455341,0,Cash loans,M,Y,N,0,225000.0,675000.0,28597.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
306723,455365,0,Cash loans,M,Y,Y,0,180000.0,301896.0,27819.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
306757,455405,0,Cash loans,F,Y,N,0,225000.0,1597500.0,45783.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
306759,455407,0,Cash loans,F,Y,N,0,108000.0,568908.0,22558.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
306771,455419,0,Revolving loans,M,Y,Y,0,450000.0,1125000.0,56250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306803,455460,0,Cash loans,F,Y,Y,0,135000.0,1386265.5,36697.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
306814,455471,0,Cash loans,F,Y,Y,0,135000.0,993082.5,47776.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306882,455551,0,Cash loans,M,Y,Y,0,517500.0,2250000.0,59485.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
306894,455563,0,Cash loans,M,Y,Y,0,360000.0,1350000.0,53671.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306908,455578,0,Cash loans,M,Y,Y,0,180000.0,284400.0,19134.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
306911,455581,0,Cash loans,M,Y,Y,0,247500.0,594261.0,51133.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
306956,455628,0,Cash loans,M,Y,Y,1,261000.0,714154.5,38871.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,2.0
306957,455629,1,Cash loans,F,Y,Y,2,135000.0,219249.0,16083.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
306967,455642,0,Cash loans,F,Y,Y,0,225000.0,550980.0,40221.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
306969,455646,0,Cash loans,F,Y,N,1,247500.0,1200744.0,38736.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
307007,455687,0,Cash loans,M,Y,Y,0,112500.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
307039,455723,0,Cash loans,F,Y,Y,0,157500.0,454500.0,43150.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307040,455724,0,Cash loans,M,Y,Y,1,202500.0,1350000.0,39474.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307149,455847,0,Cash loans,F,Y,Y,0,270000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307172,455875,0,Cash loans,M,Y,Y,0,180000.0,735579.0,40032.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
307174,455877,0,Cash loans,F,Y,N,0,135000.0,900000.0,31887.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307206,455914,0,Cash loans,F,Y,Y,0,315000.0,1066500.0,31180.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307215,455923,0,Cash loans,M,Y,N,0,157500.0,225000.0,15034.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307358,456083,0,Cash loans,F,Y,Y,2,112500.0,361462.5,16051.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307359,456084,0,Cash loans,F,Y,Y,1,99000.0,675000.0,21906.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307407,456140,1,Cash loans,F,Y,Y,1,261000.0,711454.5,47673.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
307456,456195,0,Cash loans,F,Y,Y,0,94500.0,270000.0,15075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.0,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0